services:
  customer-manager-db:
    image: bitnami/postgresql
    ports:
      - 5431:5432
    environment:
      POSTGRESQL_USERNAME: johndoe
      POSTGRESQL_PASSWORD: randompassword
      POSTGRESQL_DATABASE: customer-manager-api
